services:
  nngine:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      
  # Celery Workers
  worker:
    build: .
    command: celery -A your_project.celery worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
      - CELERY_BACKEND_URL=redis://redis:6379/0
    
  # RabbitMQ Broker
  rabbitmq:
    image: "rabbitmq:latest"  # Official RabbitMQ image
    ports:
      - "5672:5672"  # RabbitMQ broker port
      - "15672:15672"  # RabbitMQ management UI