proxy_location: HeadOnly

http_options:
  host: 0.0.0.0
  port: 8080

applications:
- name: nngine
  route_prefix: /
  import_path: app.main:head
  runtime_env:
    pip:
      - torch
      - transformers
      - nnsight