services:
  nngine:
    build:
      context: ..
      dockerfile: compose/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../core:/app/core
    command: ./app/app_start.sh
    depends_on:
      - ray

  ray:
    build:
      context: ..
      dockerfile: compose/Dockerfile
    ports:
      - "6379:6379"
      - "8265:8265"
    volumes:
      - ../app:/app/app
      - ../core:/app/core
    command: ./ray/ray_start.sh

volumes:
  app:
  core: